<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:ns="Microsoft.Xna.Framework">
  <Asset Type="GameStateManager.ResourcesList">
      <Songs>
        <Item>song</Item>
      </Songs>
      <SoundEffects>
        <Item>battle002</Item>
        <Item>battle003</Item>
        <Item>battle008</Item>
        <Item>battle011</Item>
        <Item>battle012</Item>
        <Item>cartoon002</Item>
        <Item>cartoon158</Item>
        <Item>cartoon165</Item>
        <Item>cartoon181</Item>
        <Item>catSound</Item>
        <Item>firePlace</Item>
      </SoundEffects>
      <Fonts>
        <Item>debugFont</Item>
        <Item>gameFont</Item>
        <Item>menuFont</Item>
      </Fonts>
      <Textures>
        <Item>background</Item>
        <Item>gameBackground</Item>
        <Item>pauseBackground</Item>
        <Item>whiteTexture</Item>
        <Item>noInputTexture</Item>
        <Item>controllerTexture</Item>
        <Item>keyboardTexture</Item>
        <Item>gamePad</Item>
        <Item>none</Item>
        <Item>up</Item>
        <Item>down</Item>
        <Item>left</Item>
        <Item>right</Item>
        <Item>upLeft</Item>
        <Item>upRight</Item>
        <Item>downLeft</Item>
        <Item>downRight</Item>
        <Item>aButtonPadFace</Item>
        <Item>bButtonPadFace</Item>
        <Item>xButtonPadFace</Item>
        <Item>yButtonPadFace</Item>
        <Item>aButton</Item>
        <Item>bButton</Item>
        <Item>xButton</Item>
        <Item>yButton</Item>
        <Item>lbButton</Item>
        <Item>ltButton</Item>
        <Item>rbButton</Item>
        <Item>rtButton</Item>
        <Item>windowsButton</Item>
        <Item>menuButton</Item>
        <Item>plus</Item>
        <Item>padFace</Item>
        <Item>onscreenInnerThumbstick</Item>
        <Item>onscreenOuterThumbstick</Item>
        <Item>onscreenDPadBase</Item>
        <Item>onscreenDPadDown</Item>
        <Item>onscreenDPadDownLeft</Item>
        <Item>onscreenDPadDownRight</Item>
        <Item>onscreenDPadLeft</Item>
        <Item>onscreenDPadRight</Item>
        <Item>onscreenDPadUp</Item>
        <Item>onscreenDPadUpLeft</Item>
        <Item>onscreenDPadUpRight</Item>
        <Item>defaultTexture</Item>
      </Textures>
  </Asset>
</XnaContent>